### ISSUE TITLE
关于“哌”和“呱”的拼音

### ISSUE THREAD

**Issue by LeeWang2014** [rime/rime-luna-pinyin#14]
首先说明一点，我是纯小白（医学生一枚）。

我用luna拼音输入法（小鹤双拼）打不出哌（pai，哌啶），然后发现luna-pinyin.dict.yaml中读音为pai的字中没有“哌”，我用“哌”搜了一下，发现“哌”被当作“呱”做了注音，而且词组中出现了“呱呱坠地  wa wa zhui di"这个词读做”gu gu zhui di“。

摘录疑似错误位置如下：
哌	gu
哌	gua
哌	wa

呱呱墜地	wa wa zhui di
呱呱墮地	wa wa duo di

我没有能力自己解决这个问题，希望能够得到帮助。

再次感谢开发人员，希望rime项目越来越好~~

**Comment by lotem** [comment]
鄙視樓上幾位。打這麼多字發帖，不修代碼。

**Comment by lotem** [comment]
https://www.zdic.net/hans/%E5%93%8C
gu 這個音《康熙字典》有記載的
> 【篇海】音孤。啼聲。◎按卽呱字之譌。

**Comment by dragon100a** [comment]
> 现在好像也没修复的样子

谢谢告知。这个毛病从楼主提到，迄今快1年了。



> 鄙視樓上幾位。打這麼多字發帖，不修代碼。

你的id末尾带member，看起来是组内成员咯？组内成员不作为鄙视组外成员，真厉害，无话可说。

**Comment by lotem** [comment]
@dragon100a 对。其实我指的就是这位。

一辈子也用不到的字，注音错了，何况又不是我的错（从康熙字典就错了），通常我是不管的。
而且“不管”是有依据的，已在 [授权条款](https://github.com/rime/rime-luna-pinyin/blob/master/LICENSE) 里写明。既然输入法开源了，那就全靠大家各取所需了。作者不承担任何责任。
我做开源项目是因为在网上找了很久没有人做我想要的软件。
本可以做完自己用。开源出来一方面有类似需求的人可以少写点代码，一方面我做得不好，大家都可以来完善他。
实践证明，这个模式行之有效。感谢楼主提供的线索，告诉大家这个软件存在的问题，帮助有贡献力的用家对软件做出改进。若非如此，这个问题将一直存在，当然如果没有多少人用的话，也许不会造成任何影响。
这个模式也有个副作用，就是讨论参与者的心智水平参差不齐，会产生很多噪音。乖戾者的发言往往毫无帮助，只会让真正有用的信息被水淹没，无法得到及时处理。
一直没人修，说明用这个字的人太少。
只有寥寥几人用到，其中乏人修复问题并分享出来，这丝毫不奇怪。有什么好阴阳怪气的？
你有一个好，你markdown比谁用得格式都正宗。可是你这个心态……
@nameoverflow 和 @Prcuvu 时隔四年重新发布小狼毫，比你们不知高到哪里去了，也没见这么暴躁过。

**Comment by Prcuvu** [comment]
“[wā wā zhuì dì](https://www.moedict.tw/%E5%91%B1%E5%91%B1%E5%A2%9C%E5%9C%B0)”是对岸的读法，并没有错。
朙月拼音和地球拼音的词库中词组普遍存在缺乏大陆读法的情况，请大家积极补充。
