### ISSUE TITLE
文档中定制标点符号的方法失效

### ISSUE THREAD

**Issue by AlynxZhou** [rime/rime-luna-pinyin#34]
我一直使用 <https://github.com/rime/home/wiki/CustomizationGuide#%E4%B8%80%E4%BE%8B%E5%AE%9A%E8%A3%BD%E6%A8%99%E9%BB%9E%E7%AC%A6%E8%99%9F> 提供的方法修改标点符号候选字，我的配置文件是 <https://sh.alynx.one/posts/My-RIME/default.custom.yaml>，使用的方案是 朙月拼音 简化字 版本，其中有诸如波浪线不显示候选词而是直接上屏的设定，但最近发现该设定失效了，即使 `build/default.yaml` 已经应用了 patch 里面的设置，按下波浪线仍然会显示候选词。

我使用的是 Arch Linux，经过降级软件包后发现 rime-luna-pinyin 版本为 20200920 时不存在这个问题，而 20210124 以及之后的版本都存在问题。对比之后我怀疑是如下改动造成的。

在 20200920 版本的 `/usr/share/rime-data/luna_pinyin_simp.schema.yaml` 文件内有如下设置：

```yaml
punctuator:
  import_preset: default
```

而在 20200124 版本里面这条设置被删除，改为导入 `luna_pinyin.schema.yaml` 文件内设置，这个文件里设置则是：

```yaml
punctuator:
  import_preset: symbol
```

所以想问是否由于上述改动导致无法通过给 `default.yaml` 添加 patch 来自定义标点候选字？如果是的话，该如何自定义标点候选字呢？文档是否需要更新？

**Comment by AlynxZhou** [comment]
我将 `punctuator` 部分挪到了新建的 `symbols.custom.yaml` 文件，重新部署之后工作正常，不知道这种是不是正确做法？

**Comment by AlynxZhou** [comment]
> 我将 `punctuator` 部分挪到了新建的 `symbols.custom.yaml` 文件，重新部署之后工作正常，不知道这种是不是正确做法？

这样似乎会影响 `luna_pinyin_simp.yaml` 里面导入的 symbols 的其他选项，我是否应该对 `luna_pinyin_simp` 打 patch 而不是对 `symbols` 打 patch？

**Comment by lotem** [comment]
​是的有這項修改，目的是統一這幾個差異不大的方案，避免產生不同步的修改（如你發現的這一處差異）。

文檔中推薦的做法是，修改個別符號、在輸入方案配置裏打補丁：
https://github.com/rime/home/wiki/CustomizationGuide#%E4%B8%80%E4%BE%8B%E5%AE%9A%E8%A3%BD%E6%A8%99%E9%BB%9E%E7%AC%A6%E8%99%9F
或者導入自己寫的成套符號配置。

**Comment by AlynxZhou** [comment]
> ​是的有這項修改，目的是統一這幾個差異不大的方案，避免產生不同步的修改（如你發現的這一處差異）。
> 
> 文檔中推薦的做法是，修改個別符號、在輸入方案配置裏打補丁：
> https://github.com/rime/home/wiki/CustomizationGuide#%E4%B8%80%E4%BE%8B%E5%AE%9A%E8%A3%BD%E6%A8%99%E9%BB%9E%E7%AC%A6%E8%99%9F
> 或者導入自己寫的成套符號配置。

懂了，谢谢
