### ISSUE TITLE
「剋 」念「kei」时不应该转化为「克」

### ISSUE THREAD

**Issue by tusooa** [rime/rime-luna-pinyin#41]
「剋 」念「kei」时表示「打，骂」，简化字应不转化为「克」。

例如

https://en.wiktionary.org/wiki/%E5%89%8B#Pronunciation_2 （简化字也是「剋 」）

https://www.zdic.net/hans/%E5%89%8B （有kei读音）
https://www.zdic.net/hant/%E5%85%8B （无kei读音，只有ke）

**Comment by LEOYoon-Tsaw** [comment]
這個要在OpenCC改，有固定的詞嗎？

**Comment by tusooa** [comment]
> 這個要在OpenCC改，有固定的詞嗎？

没有，「剋」通常都是单用的，自己就是一个词。
