### ISSUE TITLE
吃不應該變成喫

### ISSUE THREAD

**Issue by austin4idps** [rime/rime-luna-pinyin#43]
打我在輸入跟 `吃` 有關係打詞語時  
> chi dong xi   

會輸出喫東西   而不是 吃東西  
通過調整字典也無法解決  
或是在設定目錄底下openCC引入其他人打設定也沒辦法解決  

---
OS: MacOS 13.0
鼠鬚管: 0.15.2

**Comment by LEOYoon-Tsaw** [comment]
你可以自定義一個OpenCC標準。吃僅指口吃和吃吃笑。eat義不可寫作吃

**Comment by austin4idps** [comment]
想請問如何自定義OpenCC 找了一陣子找不到配置文件

**Comment by LEOYoon-Tsaw** [comment]
在方案中加上
```YAML
simplifier:
  opencc_config: my_opencc_config.json
  option_name: simplification
```
在用戶文件夾的`opencc`文件夾（如無則建）下新建`my_opencc_config.json`
```json
{
  "name": "Traditional To My Rules",
  "segmentation": {
    "type": "mmseg",
    "dict": {
      "type": "text",
      "file": "phrases.txt"
    }
  },
  "conversion_chain": [{
    "dict": {
      "type": "group",
      "dicts": [{
        "type": "text",
        "file": "phrases.txt"
      }, {
        "type": "text",
        "file": "characters.txt"
      }]
    }
  }]
}
```
然後分別新建`phrases.txt`和`characters.txt`放入需轉換的詞與字

**Comment by austin4idps** [comment]
感謝你的回覆

**Comment by lotem** [comment]
用OpenCC轉換是一個辦法。

起因是Rime預設詞典中的詞語寫法都儘量統一採用OpenCC的用字標準。不過你也可以在不轉換的情況下選取想要的單字手動造詞。

**Comment by austin4idps** [comment]
> 用OpenCC轉換是一個辦法。
> 
> 起因是Rime預設詞典中的詞語寫法都儘量統一採用OpenCC的用字標準。不過你也可以在不轉換的情況下選取想要的單字手動造詞。

是通過輸入 手動選取詞語嗎？
通過手動選取似乎沒有記憶效果
