### ISSUE TITLE
无法使用xuan打出“璿"这个字

### ISSUE THREAD

**Issue by zhangjiakouzf** [rime/rime-luna-pinyin#45]
大家能帮忙测试一下吗？我的系统是fedora36

**Comment by LEOYoon-Tsaw** [comment]
https://github.com/rime/rime-luna-pinyin/blob/6e677427764b542313858eaed22c2951d8ec22fe/luna_pinyin.dict.yaml#L19389

**Comment by zhangjiakouzf** [comment]
> 
谢谢回复，我在字典里面已经找到这个字了，但就是打不出来，在输入xuan以后没有这个字

**Comment by LEOYoon-Tsaw** [comment]
有可能

**Comment by zhangjiakouzf** [comment]
你能打出来吗？那些方块是什么问题，要怎样解决？

**Comment by LEOYoon-Tsaw** [comment]
換個支持的字體，總之這和本方案無關了
