### ISSUE TITLE
"璿"  的问题

### ISSUE THREAD

**Issue by zhangjiakouzf** [rime/rime-luna-pinyin#47]
接上一个问题
https://github.com/rime/rime-luna-pinyin/issues/45

最近我又确认了字体文件，使用的是NotoSansCJK，也确认过里面的字形（glyph）包含有"璿"这个字，见图
![image](https://user-images.githubusercontent.com/1612026/215700469-3292cf31-d2db-4da2-9c45-e50654265505.png)

我在自定义的配置文件中重新定义了"璿"为te，因为te这个读音的字比较少

![image](https://user-images.githubusercontent.com/1612026/215698527-0107cefa-73a0-4224-8eef-b919cffc27d1.png)
发现了下面的情况：
![image](https://user-images.githubusercontent.com/1612026/215701080-519ebb47-1e26-47e2-a721-2b2e35551080.png)
te读里面多出了一个字，就是第四个字“璇”。
现在有理由怀疑"璿"字被替换为了“璇”，但进行了配置文件搜索后没有发现有价值的线索。
请作者帮忙一起分析一下，谢谢

**Comment by zhangjiakouzf** [comment]
抱歉，刚才忘记了。

作者过年好，新年大吉大利！

**Comment by LEOYoon-Tsaw** [comment]
用了繁轉簡？

**Comment by zhangjiakouzf** [comment]
![image](https://user-images.githubusercontent.com/1612026/215791675-cb1e6347-8173-4044-b88e-31280861ee72.png)
没有用，直接是简体

**Comment by zhangjiakouzf** [comment]
![image](https://user-images.githubusercontent.com/1612026/215793491-5e0b878e-89e6-407b-8a17-a76b41fa0d8b.png)
另外刚刚发现“贷”这个字出现在te的读音里面也有些问题。

**Comment by LEOYoon-Tsaw** [comment]
肯定是開了的，關掉就打得出來了。

**Comment by zhangjiakouzf** [comment]
您是怎样关掉的？方法请告知一下，我试试看

**Comment by LEOYoon-Tsaw** [comment]
> 您是怎样关掉的？方法请告知一下，我试试看

方案選單那儿按2，再按「汉」對應的那個

**Comment by zhangjiakouzf** [comment]
谢谢，现在可以了

**Comment by zhangjiakouzf** [comment]
上面的“贷”也是同样的问题，同“貸”
