### ISSUE TITLE
「柘」「𬞟」

### ISSUE THREAD

**Issue by October22** [rime/rime-luna-pinyin#5]
### dict.yaml

* 15339「柘」 `tuo` 读音有误，只有 `zhe4` 读音。参考 http://www.zdic.net/z/1b/js/67D8.htm
* 「𬞟」，`pin2` 18030 中新增，「白𬞟」，蘋的简体。参考 http://yedict.com/zscontent.asp?uni=860B

**Comment by LEOYoon-Tsaw** [comment]
柘已處理，簡化字通過OpenCC轉化，字典不收。
