### ISSUE TITLE
閪字读音应当增加xi1、hei1

### ISSUE THREAD

**Issue by Ecauchy** [rime/rime-luna-pinyin#62]
粤语字閪（𲈹）

《汉语方言大词典》书证 hei1
<img width="462" alt="image" src="https://github.com/rime/rime-luna-pinyin/assets/7821408/e903f46f-f124-4bc0-abad-947faa976599">

《字海》书证 xi1
<img width="691" alt="image" src="https://github.com/rime/rime-luna-pinyin/assets/7821408/68cc9f54-5124-4de2-aab7-9b3e814408d2">

**Comment by Ecauchy** [comment]
目前方案里给的se音实际上是韩语国字读音不知道是怎么弄的转过来的，并不是这个粤语字对应的读音。

**Comment by LEOYoon-Tsaw** [comment]
首先，粵語的讀音加入粵拼就行了嘛（據我所知早就有了）；
其次，而且粵語讀hai1的音對應官話應該是xī。
