### ISSUE TITLE
'怯' is not 'que'

### ISSUE THREAD

**Issue by sgalal** [rime/rime-luna-pinyin#9]
'怯' should be 'qie', but there are many occurrences of 'que'.

https://github.com/rime/rime-luna-pinyin/blob/master/luna_pinyin.dict.yaml#L12793

https://github.com/rime/rime-luna-pinyin/blob/master/luna_pinyin.dict.yaml#L51583

and so on.

**Comment by lotem** [comment]
One data source provides this pronunciation: 
https://www.moedict.tw/%E6%80%AF

The phrase entry should be removed:
https://github.com/rime/rime-luna-pinyin/blob/master/luna_pinyin.dict.yaml#L51583
